-- MySQL Script generated by MySQL Workbench
-- 04/29/17 16:42:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema casalimpa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `casalimpa` ;

-- -----------------------------------------------------
-- Schema casalimpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casalimpa` DEFAULT CHARACTER SET utf8 ;
USE `casalimpa` ;

-- -----------------------------------------------------
-- Table `casalimpa`.`categoria_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`categoria_servico` (
  `cod_categoria_servico` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(105) NOT NULL,
  `nivel_dificuldade` BIGINT(20) NOT NULL,
  PRIMARY KEY (`cod_categoria_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`situacao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`situacao_usuario` (
  `idsituacao_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idsituacao_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`tb_uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`tb_uf` (
  `Sigla_UF` CHAR(2) NOT NULL,
  `Nome_Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Sigla_UF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`tb_cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`tb_cidade` (
  `PK_Cidade` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Cidade` VARCHAR(45) NOT NULL,
  `TB_UF_Sigla_UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`PK_Cidade`),
  INDEX `fk_TB_Cidade_TB_UF1_idx` (`TB_UF_Sigla_UF` ASC),
  CONSTRAINT `fk_TB_Cidade_TB_UF1`
    FOREIGN KEY (`TB_UF_Sigla_UF`)
    REFERENCES `casalimpa`.`tb_uf` (`Sigla_UF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`tb_bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`tb_bairro` (
  `PK_Bairro` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Bairro` VARCHAR(45) NOT NULL,
  `TB_Cidade_PK_Cidade` INT(11) NOT NULL,
  PRIMARY KEY (`PK_Bairro`),
  INDEX `fk_TB_Bairro_TB_Cidade1_idx` (`TB_Cidade_PK_Cidade` ASC),
  CONSTRAINT `fk_TB_Bairro_TB_Cidade1`
    FOREIGN KEY (`TB_Cidade_PK_Cidade`)
    REFERENCES `casalimpa`.`tb_cidade` (`PK_Cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`tb_logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`tb_logradouro` (
  `PK_Logradouro` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_logradouro` VARCHAR(45) NOT NULL,
  `CEP_Logradouro` VARCHAR(45) NOT NULL,
  `TB_Bairro_PK_Bairro` INT(11) NOT NULL,
  PRIMARY KEY (`PK_Logradouro`),
  INDEX `fk_TB_Logradouro_TB_Bairro1_idx` (`TB_Bairro_PK_Bairro` ASC),
  CONSTRAINT `fk_TB_Logradouro_TB_Bairro1`
    FOREIGN KEY (`TB_Bairro_PK_Bairro`)
    REFERENCES `casalimpa`.`tb_bairro` (`PK_Bairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`usuario` (
  `id_usuario` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(105) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `expiracao` DATE NOT NULL,
  `idsituacao` INT(11) NOT NULL,
  `fotoPerfil` BLOB NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `tb_logradouro_PK_Logradouro` INT(11) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_situacao_usuario1_idx` (`idsituacao` ASC),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_usuario_tb_logradouro1_idx` (`tb_logradouro_PK_Logradouro` ASC),
  CONSTRAINT `fk_usuario_situacao_usuario1`
    FOREIGN KEY (`idsituacao`)
    REFERENCES `casalimpa`.`situacao_usuario` (`idsituacao_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tb_logradouro1`
    FOREIGN KEY (`tb_logradouro_PK_Logradouro`)
    REFERENCES `casalimpa`.`tb_logradouro` (`PK_Logradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`cliente` (
  `id_cliente` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `telefone` INT(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_usuario` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `casalimpa`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`contrato_prestacao_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`contrato_prestacao_servico` (
  `numero_contrato` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `valor_principal` DOUBLE NOT NULL,
  `observacoes` TEXT NOT NULL,
  `descricao` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`numero_contrato`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`profissional` (
  `id_profissional` INT(45) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `registro_salarial` VARCHAR(20) NULL,
  `area_atuacao` VARCHAR(90) NULL,
  `id_usuario` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_profissional`),
  INDEX `fk_profissional_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_profissional_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `casalimpa`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`situacao_os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`situacao_os` (
  `idsituacao_os` INT(11) NOT NULL AUTO_INCREMENT,
  `situacao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idsituacao_os`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`ordem_servico` (
  `id_os` INT(10) NOT NULL AUTO_INCREMENT,
  `numero_os` BIGINT(20) NOT NULL,
  `dt_inicio` DATE NOT NULL,
  `dt_fim` DATE NOT NULL,
  `turno_pref` VARCHAR(10) NOT NULL,
  `horario` TIME NOT NULL,
  `profissional_usuario_cod_usuario` INT(11) NOT NULL,
  `cliente_usuario_cod_usuario` BIGINT(20) NOT NULL,
  `contrato_prestacao_servico_numero_contrato` BIGINT(20) NULL DEFAULT NULL,
  `situacao_os_idsituacao_os` INT(11) NOT NULL,
  `profissional_id_usuario` INT(45) NOT NULL,
  `Endereco_idEndereco` INT(11) NOT NULL,
  `usuario_id_usuario` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_os`),
  INDEX `fk_ordem_servico_cliente1_idx` (`cliente_usuario_cod_usuario` ASC),
  INDEX `fk_ordem_servico_contrato_prestacao_servico1_idx` (`contrato_prestacao_servico_numero_contrato` ASC),
  INDEX `fk_ordem_servico_situacao_os1_idx` (`situacao_os_idsituacao_os` ASC),
  INDEX `fk_ordem_servico_profissional1_idx` (`profissional_id_usuario` ASC),
  INDEX `fk_ordem_servico_usuario1_idx` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `numero_os_UNIQUE` (`numero_os` ASC),
  CONSTRAINT `fk_ordem_servico_cliente1`
    FOREIGN KEY (`cliente_usuario_cod_usuario`)
    REFERENCES `casalimpa`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_contrato_prestacao_servico1`
    FOREIGN KEY (`contrato_prestacao_servico_numero_contrato`)
    REFERENCES `casalimpa`.`contrato_prestacao_servico` (`numero_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_profissional1`
    FOREIGN KEY (`profissional_id_usuario`)
    REFERENCES `casalimpa`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_situacao_os1`
    FOREIGN KEY (`situacao_os_idsituacao_os`)
    REFERENCES `casalimpa`.`situacao_os` (`idsituacao_os`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `casalimpa`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`qualificacao_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`qualificacao_cliente` (
  `cod_qualificacao` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `media_satisfatoria` INT(11) NOT NULL,
  `cliente_usuario_cod_usuario` BIGINT(20) NOT NULL,
  `ordem_servico_numero_os` BIGINT(20) NOT NULL,
  PRIMARY KEY (`cod_qualificacao`),
  INDEX `fk_qualificacao_cliente_cliente1_idx` (`cliente_usuario_cod_usuario` ASC),
  INDEX `fk_qualificacao_cliente_ordem_servico1_idx` (`ordem_servico_numero_os` ASC),
  CONSTRAINT `fk_qualificacao_cliente_cliente1`
    FOREIGN KEY (`cliente_usuario_cod_usuario`)
    REFERENCES `casalimpa`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualificacao_cliente_ordem_servico1`
    FOREIGN KEY (`ordem_servico_numero_os`)
    REFERENCES `casalimpa`.`ordem_servico` (`numero_os`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`qualificacao_profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`qualificacao_profissional` (
  `cod_qualificacao` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `total_reclamacoes` INT(11) NOT NULL,
  `total_satisfeitos` INT(11) NOT NULL,
  `media_atendimento` INT(11) NOT NULL,
  `profissional_usuario_cod_usuario` INT(11) NOT NULL,
  `profissional_id_usuario` INT(45) NOT NULL,
  PRIMARY KEY (`cod_qualificacao`),
  INDEX `fk_qualificacao_profissional_profissional1_idx` (`profissional_id_usuario` ASC),
  CONSTRAINT `fk_qualificacao_profissional_profissional1`
    FOREIGN KEY (`profissional_id_usuario`)
    REFERENCES `casalimpa`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`qualificacao_servico_prestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`qualificacao_servico_prestado` (
  `numero_qualificacao` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nota` INT(11) NOT NULL,
  `consideracoes` TEXT NOT NULL,
  `avaliacao` VARCHAR(45) NOT NULL,
  `ordem_servico_numero_os` BIGINT(20) NOT NULL,
  `profissional_usuario_cod_usuario` BIGINT(20) NOT NULL,
  `profissional_id_usuario` INT(45) NOT NULL,
  PRIMARY KEY (`numero_qualificacao`),
  INDEX `fk_qualificacao_servico_prestado_ordem_servico1_idx` (`ordem_servico_numero_os` ASC),
  INDEX `fk_qualificacao_servico_prestado_profissional1_idx` (`profissional_id_usuario` ASC),
  CONSTRAINT `fk_qualificacao_servico_prestado_ordem_servico1`
    FOREIGN KEY (`ordem_servico_numero_os`)
    REFERENCES `casalimpa`.`ordem_servico` (`numero_os`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qualificacao_servico_prestado_profissional1`
    FOREIGN KEY (`profissional_id_usuario`)
    REFERENCES `casalimpa`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `casalimpa`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casalimpa`.`servico` (
  `cod_sevico` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `prazo` VARCHAR(45) NOT NULL,
  `observacoes` VARCHAR(125) NOT NULL,
  `preco_sugerido` DOUBLE NOT NULL,
  `categoria_servico_cod_categoria_servico` BIGINT(20) NOT NULL,
  `profissional_usuario_cod_usuario` INT(11) NOT NULL,
  `profissional_id_usuario` INT(45) NOT NULL,
  PRIMARY KEY (`cod_sevico`),
  INDEX `fk_servico_categoria_servico1_idx` (`categoria_servico_cod_categoria_servico` ASC),
  INDEX `fk_servico_profissional1_idx` (`profissional_id_usuario` ASC),
  CONSTRAINT `fk_servico_categoria_servico1`
    FOREIGN KEY (`categoria_servico_cod_categoria_servico`)
    REFERENCES `casalimpa`.`categoria_servico` (`cod_categoria_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servico_profissional1`
    FOREIGN KEY (`profissional_id_usuario`)
    REFERENCES `casalimpa`.`profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
